### ISSUE TITLE
Calculator is broken due to Netlify NextJS runtime issue

### ISSUE THREAD

**Issue by ipr0310** [fomplo/website#2]
**Describe the problem**
As an breaking error is happening on Next.JS app
![image](https://github.com/fomplo/website/assets/35440957/7ef50950-6619-4a06-ba7f-95b97b8f5384)

That error is happening because of Netlify NextJS runtime, we can see the unsolved issue here:
https://github.com/netlify/next-runtime/issues/2329

**Possible solutions**
Based on that open ticket, temporary downgrading nextjs version could solve the issue

**Comment by ipr0310** [comment]
Server Log from netlify:
```
Jan 2, 05:09:03 AM: f9e605dd ERROR   ⨯ Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/amp-context'
Require stack:
- /var/task/node_modules/next/dist/shared/lib/head.js
- /var/task/node_modules/next/head.js
- /var/task/.next/server/pages/_app.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js
- /var/task/___netlify-handler.js
- /var/runtime/index.mjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:62:32)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/var/task/node_modules/next/dist/shared/lib/head.js:29:34)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next/dist/shared/lib/head.js',
    '/var/task/node_modules/next/head.js',
    '/var/task/.next/server/pages/_app.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js',
    '/var/task/___netlify-handler.js',
    '/var/runtime/index.mjs'
  ]
}
```
